<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin Area</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../public/style.css">

    <style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
</head>

<body>

    <div class="nav-scroller py-1 mb-2">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link text-white" href="/dashboard">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="/add-post">Add Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="/add-category">Add Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="/">Visit Blog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="container">
        <form method="POST" action="/update-post?id=<?= $id ?>">
            <div class="form-group">
                <label>Post Title</label>
                <input name="title" type="text" class="form-control" placeholder="Enter Title"
                    value="<?= $post['title']?>">
            </div>
            <div class="form-group">
                <label>Post Body</label>
                <textarea name="text" class="form-control" placeholder="Enter Post Body"><?=$post['body']?></textarea>
            </div>
            <div class="form-group">
                <label>Category</label>
                <select name="category" class="form-control">
                    <?php foreach($categories as $category): ?>
                    <option <?php $category['id'] == $post['category']?'selected':''?> value="<?=$category['id']?>">
                        <?=$category['name']?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label>Author</label>
                <input name="author" type="text" class="form-control" placeholder="Enter Author Name"
                    value="<?= $post['author']?>">
            </div>
            <div class="form-group">
                <label>Tags</label>
                <input name="tags" type="text" class="form-control" placeholder="Enter Tags"
                    value="<?= $post['tags']?>">
            </div> 
            <div class="form-group">
            <button name="submit" type="submit" class="btn btn-primary float-left mr-2">Submit</button>
            <a href="/dashboard" class="btn btn-primary float-left mr-2">Cancel</a>
            </form>
            <form action="/delete-post?id=<?= $id ?>" method="POST">
            <button name="delete" type="submit" class="btn btn-danger float-left">Delete</button>
            </form>
            </div>
    </div>
    <footer class="blog-footer text-center mt-5">
        <p>PHPLoversBlog &copy; 2019 </p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>    
</body>

</html>