<?php include 'includes/header.php'; ?>
<main role="main" class="container">
    <div class="row">
        <div class="col-12 col-md-8 blog-main">
            <?php if($posts): ?>
            <?php foreach($posts as $post) :?>
            <div class="blog-post mb-5 mt-5">
                <h2 class="blog-post-title mt-5"><?= $post['title']?></h2>
                <p class="blog-post-meta mt-3"><?= formatDate($post['date'])?> by <a href="#"><?= $post['author']?></a></p>
                <p class="text-justify mt-3"><?= shortenText($post['body']) ?></p>
                <a class="readmore mt-5 mb-5" href="/single-post?id=<?= $post['id']?>">Read More</a>

            </div><!-- /.blog-post -->
            <?php endforeach; ?>
            <?php else: ?>
            <p>There are no posts yet</p>
            <?php endif; ?>
        </div><!-- /.blog-main -->
        <?php include 'includes/footer.php'; ?>